# Generated by Django 5.1.5 on 2025-01-25 22:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RecyclingCenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=255)),
                ('url_maps', models.URLField()),
                ('contact_info', models.CharField(max_length=100)),
                ('plastic_price_per_kg', models.FloatField(default=0.0)),
                ('glass_price_per_kg', models.FloatField(default=0.0)),
                ('cardboard_price_per_kg', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='RecyclingData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material', models.CharField(choices=[('Plastic', 'Plástico'), ('Glass', 'Vidrio'), ('Cardboard', 'Cartón')], max_length=20)),
                ('weight', models.FloatField()),
                ('volume', models.FloatField()),
                ('date_collected', models.DateField()),
                ('location', models.CharField(max_length=255)),
                ('collector_name', models.CharField(blank=True, max_length=100, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('user_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
