# Generated by Django 5.1.5 on 2025-01-26 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recycleapp', '0002_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recyclingdata',
            old_name='user_id',
            new_name='user',
        ),
    ]
