# Generated by Django 5.1.5 on 2025-01-27 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recycleapp', '0004_alter_recyclingdata_date_collected'),
    ]

    operations = [
        migrations.AddField(
            model_name='recyclingdata',
            name='density',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
