# Generated by Django 5.1.5 on 2025-01-27 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recycleapp', '0005_recyclingdata_density'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recyclingdata',
            name='material',
            field=models.CharField(choices=[('Plástico', 'Plástico'), ('Vidrio', 'Vidrio'), ('Cartón', 'Cartón')], max_length=20),
        ),
    ]
