# Generated by Django 5.1.5 on 2025-01-27 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recycleapp', '0006_alter_recyclingdata_material'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recyclingcenter',
            name='url_maps',
            field=models.URLField(max_length=1000),
        ),
    ]
