# Generated by Django 5.1.5 on 2025-01-27 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recycleapp', '0007_alter_recyclingcenter_url_maps'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recyclingcenter',
            name='contact_info',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
