# Generated by Django 5.1.5 on 2025-01-27 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recycleapp', '0008_alter_recyclingcenter_contact_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recyclingcenter',
            name='cardboard_price_per_kg',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='recyclingcenter',
            name='glass_price_per_kg',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='recyclingcenter',
            name='plastic_price_per_kg',
            field=models.FloatField(),
        ),
    ]
