# Generated by Django 5.1.5 on 2025-01-27 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recycleapp', '0009_alter_recyclingcenter_cardboard_price_per_kg_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recyclingdata',
            name='claimed',
            field=models.BooleanField(default=False),
        ),
    ]
