# Generated by Django 5.1.5 on 2025-01-27 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recycleapp', '0010_recyclingdata_claimed'),
    ]

    operations = [
        migrations.AddField(
            model_name='recyclingdata',
            name='money',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
