# Generated by Django 5.1.5 on 2025-01-28 01:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recycleapp', '0011_recyclingdata_money'),
    ]

    operations = [
        migrations.AddField(
            model_name='recyclingcenter',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recyclingcenter',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
