# Generated by Django 5.1.5 on 2025-01-28 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recycleapp', '0012_recyclingcenter_created_recyclingcenter_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='recyclingdata',
            name='moneyGlass',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='recyclingdata',
            name='moneyPlastic',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='recyclingdata',
            name='money_cardboard',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='recyclingdata',
            name='money',
            field=models.FloatField(default=0),
        ),
    ]
