# Generated by Django 5.1.5 on 2025-01-30 01:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recycleapp', '0013_recyclingdata_moneyglass_recyclingdata_moneyplastic_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recyclingdata',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recyclingdata',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
