# Generated by Django 5.1.5 on 2025-01-30 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recycleapp', '0014_recyclingdata_created_recyclingdata_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='recyclingdata',
            name='recolected',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
