# Generated by Django 5.1.5 on 2025-02-10 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recycleapp', '0015_recyclingdata_recolected'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recyclingdata',
            name='volume',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
