# Generated by Django 5.1.5 on 2025-02-10 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recycleapp', '0016_alter_recyclingdata_volume'),
    ]

    operations = [
        migrations.AddField(
            model_name='recyclingdata',
            name='city',
            field=models.CharField(choices=[('Cuenca', 'Cuenca'), ('Guaranda', 'Guaranda'), ('Azogues', 'Azogues'), ('Tulcán', 'Tulcán'), ('Riobamba', 'Riobamba'), ('Latacunga', 'Latacunga'), ('Machala', 'Machala'), ('Esmeraldas', 'Esmeraldas'), ('Puerto Baquerizo Moreno', 'Puerto Baquerizo Moreno'), ('Guayaquil', 'Guayaquil'), ('Ibarra', 'Ibarra'), ('Loja', 'Loja'), ('Babahoyo', 'Babahoyo'), ('Portoviejo', 'Portoviejo'), ('Macas', 'Macas'), ('Tena', 'Tena'), ('Puerto Francisco de Orellana', 'Puerto Francisco de Orellana'), ('Puyo', 'Puyo'), ('Quito', 'Quito'), ('Santa Elena', 'Santa Elena'), ('Santo Domingo', 'Santo Domingo'), ('Nueva Loja', 'Nueva Loja'), ('Ambato', 'Ambato'), ('Zamora', 'Zamora')], default='Sin Especificar', max_length=50),
        ),
        migrations.AddField(
            model_name='recyclingdata',
            name='province',
            field=models.CharField(choices=[('Azuay', 'Azuay'), ('Bolívar', 'Bolívar'), ('Cañar', 'Cañar'), ('Carchi', 'Carchi'), ('Chimborazo', 'Chimborazo'), ('Cotopaxi', 'Cotopaxi'), ('El Oro', 'El Oro'), ('Esmeraldas', 'Esmeraldas'), ('Galápagos', 'Galápagos'), ('Guayas', 'Guayas'), ('Imbabura', 'Imbabura'), ('Loja', 'Loja'), ('Los Ríos', 'Los Ríos'), ('Manabí', 'Manabí'), ('Morona Santiago', 'Morona Santiago'), ('Napo', 'Napo'), ('Orellana', 'Orellana'), ('Pastaza', 'Pastaza'), ('Pichincha', 'Pichincha'), ('Santa Elena', 'Santa Elena'), ('Santo Domingo de los Tsáchilas', 'Santo Domingo de los Tsáchilas'), ('Sucumbíos', 'Sucumbíos'), ('Tungurahua', 'Tungurahua'), ('Zamora Chinchipe', 'Zamora Chinchipe')], default='Sin Especificar', max_length=50),
        ),
        migrations.AddField(
            model_name='recyclingdata',
            name='sector',
            field=models.CharField(choices=[('Urbano', 'Urbano'), ('Rural', 'Rural'), ('Norte', 'Norte'), ('Sur', 'Sur'), ('Centro', 'Centro'), ('Este', 'Este'), ('Oeste', 'Oeste')], default='Sin Especificar', max_length=50),
        ),
    ]
